"""initial schema

Revision ID: 8400307f3e4b
Revises: 
Create Date: 2026-08-02 18:22:49.022591
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '8400307f3e4b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('households',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('validation_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('errors', sa.JSON(), nullable=False),
    sa.Column('warnings', sa.JSON(), nullable=False),
    sa.Column('can_approve', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_results_entity_id'), 'validation_results', ['entity_id'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=True),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_event_type'), 'audit_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_events_user_id'), 'audit_events', ['user_id'], unique=False)
    op.create_table('household_members',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('household_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('household_id', 'user_id')
    )
    op.create_index(op.f('ix_household_members_household_id'), 'household_members', ['household_id'], unique=False)
    op.create_index(op.f('ix_household_members_user_id'), 'household_members', ['user_id'], unique=False)
    op.create_table('import_batches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('source_type', sa.String(length=16), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_batches_user_id'), 'import_batches', ['user_id'], unique=False)
    op.create_table('import_mapping_templates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('mapping', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_mapping_templates_user_id'), 'import_mapping_templates', ['user_id'], unique=False)
    op.create_table('ingestion_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('job_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('progress', sa.JSON(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_jobs_idempotency_key'), 'ingestion_jobs', ['idempotency_key'], unique=False)
    op.create_index(op.f('ix_ingestion_jobs_status'), 'ingestion_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_ingestion_jobs_user_id'), 'ingestion_jobs', ['user_id'], unique=False)
    op.create_table('pantry_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('normalized_name', sa.String(length=180), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'normalized_name')
    )
    op.create_index(op.f('ix_pantry_items_user_id'), 'pantry_items', ['user_id'], unique=False)
    op.create_table('recipes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_user_id', sa.String(length=36), nullable=True),
    sa.Column('household_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=240), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('photo_url', sa.Text(), nullable=True),
    sa.Column('photo_source_url', sa.Text(), nullable=True),
    sa.Column('photo_attribution', sa.Text(), nullable=True),
    sa.Column('servings', sa.Integer(), nullable=False),
    sa.Column('prep_minutes', sa.Integer(), nullable=True),
    sa.Column('cook_minutes', sa.Integer(), nullable=True),
    sa.Column('total_minutes', sa.Integer(), nullable=True),
    sa.Column('difficulty', sa.String(length=32), nullable=False),
    sa.Column('cuisine', sa.String(length=80), nullable=True),
    sa.Column('meal_type', sa.String(length=64), nullable=False),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('source_title', sa.Text(), nullable=True),
    sa.Column('original_imported_row', sa.JSON(), nullable=True),
    sa.Column('import_batch_id', sa.String(length=36), nullable=True),
    sa.Column('validation_status', sa.String(length=32), nullable=False),
    sa.Column('validation_warnings', sa.JSON(), nullable=False),
    sa.Column('duplicate_status', sa.String(length=32), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('ai_confidence', sa.JSON(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('image_status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipes_content_hash'), 'recipes', ['content_hash'], unique=False)
    op.create_index(op.f('ix_recipes_household_id'), 'recipes', ['household_id'], unique=False)
    op.create_index(op.f('ix_recipes_import_batch_id'), 'recipes', ['import_batch_id'], unique=False)
    op.create_index(op.f('ix_recipes_name'), 'recipes', ['name'], unique=False)
    op.create_index('ix_recipes_owner_status', 'recipes', ['owner_user_id', 'validation_status', 'archived_at'], unique=False)
    op.create_index(op.f('ix_recipes_owner_user_id'), 'recipes', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_recipes_source_type'), 'recipes', ['source_type'], unique=False)
    op.create_index(op.f('ix_recipes_validation_status'), 'recipes', ['validation_status'], unique=False)
    op.create_table('retailer_product_preferences',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('normalized_name', sa.String(length=180), nullable=False),
    sa.Column('retailer', sa.String(length=64), nullable=False),
    sa.Column('product_id', sa.String(length=120), nullable=True),
    sa.Column('product_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_retailer_product_preferences_user_id'), 'retailer_product_preferences', ['user_id'], unique=False)
    op.create_table('user_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('household_id', sa.String(length=36), nullable=True),
    sa.Column('household_size', sa.Integer(), nullable=False),
    sa.Column('weekly_meal_target', sa.Integer(), nullable=False),
    sa.Column('max_cook_minutes', sa.Integer(), nullable=True),
    sa.Column('difficulty_preference', sa.String(length=32), nullable=True),
    sa.Column('dietary_preferences', sa.JSON(), nullable=False),
    sa.Column('allergens', sa.JSON(), nullable=False),
    sa.Column('disliked_ingredients', sa.JSON(), nullable=False),
    sa.Column('favorite_proteins', sa.JSON(), nullable=False),
    sa.Column('budget_preference', sa.String(length=32), nullable=True),
    sa.Column('walmart_zip', sa.String(length=16), nullable=True),
    sa.Column('notification_preferences', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profiles_user_id'), 'user_profiles', ['user_id'], unique=True)
    op.create_table('weekly_plans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('meal_target', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'week_start')
    )
    op.create_index(op.f('ix_weekly_plans_user_id'), 'weekly_plans', ['user_id'], unique=False)
    op.create_index(op.f('ix_weekly_plans_week_start'), 'weekly_plans', ['week_start'], unique=False)
    op.create_table('favorites',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('recipe_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'recipe_id')
    )
    op.create_index(op.f('ix_favorites_recipe_id'), 'favorites', ['recipe_id'], unique=False)
    op.create_index(op.f('ix_favorites_user_id'), 'favorites', ['user_id'], unique=False)
    op.create_table('grocery_lists',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('weekly_plan_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['weekly_plan_id'], ['weekly_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grocery_lists_user_id'), 'grocery_lists', ['user_id'], unique=False)
    op.create_index(op.f('ix_grocery_lists_weekly_plan_id'), 'grocery_lists', ['weekly_plan_id'], unique=False)
    op.create_table('hidden_recipes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('recipe_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'recipe_id')
    )
    op.create_index(op.f('ix_hidden_recipes_recipe_id'), 'hidden_recipes', ['recipe_id'], unique=False)
    op.create_index(op.f('ix_hidden_recipes_user_id'), 'hidden_recipes', ['user_id'], unique=False)
    op.create_table('import_files',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('import_batch_id', sa.String(length=36), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=120), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('stored_path', sa.Text(), nullable=False),
    sa.Column('headers', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_files_import_batch_id'), 'import_files', ['import_batch_id'], unique=False)
    op.create_table('import_rows',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('import_batch_id', sa.String(length=36), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=False),
    sa.Column('normalized_data', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('duplicate_status', sa.String(length=32), nullable=False),
    sa.Column('warnings', sa.JSON(), nullable=False),
    sa.Column('committed_recipe_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_rows_import_batch_id'), 'import_rows', ['import_batch_id'], unique=False)
    op.create_table('meal_swipes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('recipe_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meal_swipes_recipe_id'), 'meal_swipes', ['recipe_id'], unique=False)
    op.create_index(op.f('ix_meal_swipes_session_id'), 'meal_swipes', ['session_id'], unique=False)
    op.create_index(op.f('ix_meal_swipes_user_id'), 'meal_swipes', ['user_id'], unique=False)
    op.create_table('recipe_ingredients',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('recipe_id', sa.String(length=36), nullable=False),
    sa.Column('original_text', sa.Text(), nullable=False),
    sa.Column('normalized_name', sa.String(length=180), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('preparation_note', sa.String(length=255), nullable=True),
    sa.Column('is_optional', sa.Boolean(), nullable=False),
    sa.Column('section', sa.String(length=120), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipe_ingredients_normalized_name'), 'recipe_ingredients', ['normalized_name'], unique=False)
    op.create_index(op.f('ix_recipe_ingredients_recipe_id'), 'recipe_ingredients', ['recipe_id'], unique=False)
    op.create_table('recipe_instruction_steps',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('recipe_id', sa.String(length=36), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('section', sa.String(length=120), nullable=True),
    sa.Column('timer_minutes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipe_instruction_steps_recipe_id'), 'recipe_instruction_steps', ['recipe_id'], unique=False)
    op.create_table('recipe_photos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('recipe_id', sa.String(length=36), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('attribution', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipe_photos_recipe_id'), 'recipe_photos', ['recipe_id'], unique=False)
    op.create_table('recipe_sources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('recipe_id', sa.String(length=36), nullable=False),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('source_title', sa.Text(), nullable=True),
    sa.Column('provenance', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipe_sources_recipe_id'), 'recipe_sources', ['recipe_id'], unique=False)
    op.create_table('recipe_tags',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('recipe_id', sa.String(length=36), nullable=False),
    sa.Column('tag', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recipe_id', 'tag')
    )
    op.create_index(op.f('ix_recipe_tags_recipe_id'), 'recipe_tags', ['recipe_id'], unique=False)
    op.create_index(op.f('ix_recipe_tags_tag'), 'recipe_tags', ['tag'], unique=False)
    op.create_table('recipe_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('recipe_id', sa.String(length=36), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipe_versions_recipe_id'), 'recipe_versions', ['recipe_id'], unique=False)
    op.create_table('url_ingestion_candidates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('extracted_data', sa.JSON(), nullable=False),
    sa.Column('raw_snapshot', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('validation_warnings', sa.JSON(), nullable=False),
    sa.Column('approved_recipe_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['ingestion_jobs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_url_ingestion_candidates_user_id'), 'url_ingestion_candidates', ['user_id'], unique=False)
    op.create_table('weekly_plan_slots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('weekly_plan_id', sa.String(length=36), nullable=False),
    sa.Column('slot_date', sa.Date(), nullable=True),
    sa.Column('slot_type', sa.String(length=32), nullable=False),
    sa.Column('recipe_id', sa.String(length=36), nullable=True),
    sa.Column('servings', sa.Integer(), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.ForeignKeyConstraint(['weekly_plan_id'], ['weekly_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weekly_plan_slots_weekly_plan_id'), 'weekly_plan_slots', ['weekly_plan_id'], unique=False)
    op.create_table('grocery_list_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('grocery_list_id', sa.String(length=36), nullable=False),
    sa.Column('normalized_name', sa.String(length=180), nullable=False),
    sa.Column('display_name', sa.String(length=180), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('is_checked', sa.Boolean(), nullable=False),
    sa.Column('walmart_search_url', sa.Text(), nullable=True),
    sa.Column('match_status', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['grocery_list_id'], ['grocery_lists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grocery_list_items_grocery_list_id'), 'grocery_list_items', ['grocery_list_id'], unique=False)
    op.create_table('import_row_errors',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('import_row_id', sa.String(length=36), nullable=False),
    sa.Column('field', sa.String(length=80), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['import_row_id'], ['import_rows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_row_errors_import_row_id'), 'import_row_errors', ['import_row_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_import_row_errors_import_row_id'), table_name='import_row_errors')
    op.drop_table('import_row_errors')
    op.drop_index(op.f('ix_grocery_list_items_grocery_list_id'), table_name='grocery_list_items')
    op.drop_table('grocery_list_items')
    op.drop_index(op.f('ix_weekly_plan_slots_weekly_plan_id'), table_name='weekly_plan_slots')
    op.drop_table('weekly_plan_slots')
    op.drop_index(op.f('ix_url_ingestion_candidates_user_id'), table_name='url_ingestion_candidates')
    op.drop_table('url_ingestion_candidates')
    op.drop_index(op.f('ix_recipe_versions_recipe_id'), table_name='recipe_versions')
    op.drop_table('recipe_versions')
    op.drop_index(op.f('ix_recipe_tags_tag'), table_name='recipe_tags')
    op.drop_index(op.f('ix_recipe_tags_recipe_id'), table_name='recipe_tags')
    op.drop_table('recipe_tags')
    op.drop_index(op.f('ix_recipe_sources_recipe_id'), table_name='recipe_sources')
    op.drop_table('recipe_sources')
    op.drop_index(op.f('ix_recipe_photos_recipe_id'), table_name='recipe_photos')
    op.drop_table('recipe_photos')
    op.drop_index(op.f('ix_recipe_instruction_steps_recipe_id'), table_name='recipe_instruction_steps')
    op.drop_table('recipe_instruction_steps')
    op.drop_index(op.f('ix_recipe_ingredients_recipe_id'), table_name='recipe_ingredients')
    op.drop_index(op.f('ix_recipe_ingredients_normalized_name'), table_name='recipe_ingredients')
    op.drop_table('recipe_ingredients')
    op.drop_index(op.f('ix_meal_swipes_user_id'), table_name='meal_swipes')
    op.drop_index(op.f('ix_meal_swipes_session_id'), table_name='meal_swipes')
    op.drop_index(op.f('ix_meal_swipes_recipe_id'), table_name='meal_swipes')
    op.drop_table('meal_swipes')
    op.drop_index(op.f('ix_import_rows_import_batch_id'), table_name='import_rows')
    op.drop_table('import_rows')
    op.drop_index(op.f('ix_import_files_import_batch_id'), table_name='import_files')
    op.drop_table('import_files')
    op.drop_index(op.f('ix_hidden_recipes_user_id'), table_name='hidden_recipes')
    op.drop_index(op.f('ix_hidden_recipes_recipe_id'), table_name='hidden_recipes')
    op.drop_table('hidden_recipes')
    op.drop_index(op.f('ix_grocery_lists_weekly_plan_id'), table_name='grocery_lists')
    op.drop_index(op.f('ix_grocery_lists_user_id'), table_name='grocery_lists')
    op.drop_table('grocery_lists')
    op.drop_index(op.f('ix_favorites_user_id'), table_name='favorites')
    op.drop_index(op.f('ix_favorites_recipe_id'), table_name='favorites')
    op.drop_table('favorites')
    op.drop_index(op.f('ix_weekly_plans_week_start'), table_name='weekly_plans')
    op.drop_index(op.f('ix_weekly_plans_user_id'), table_name='weekly_plans')
    op.drop_table('weekly_plans')
    op.drop_index(op.f('ix_user_profiles_user_id'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_retailer_product_preferences_user_id'), table_name='retailer_product_preferences')
    op.drop_table('retailer_product_preferences')
    op.drop_index(op.f('ix_recipes_validation_status'), table_name='recipes')
    op.drop_index(op.f('ix_recipes_source_type'), table_name='recipes')
    op.drop_index(op.f('ix_recipes_owner_user_id'), table_name='recipes')
    op.drop_index('ix_recipes_owner_status', table_name='recipes')
    op.drop_index(op.f('ix_recipes_name'), table_name='recipes')
    op.drop_index(op.f('ix_recipes_import_batch_id'), table_name='recipes')
    op.drop_index(op.f('ix_recipes_household_id'), table_name='recipes')
    op.drop_index(op.f('ix_recipes_content_hash'), table_name='recipes')
    op.drop_table('recipes')
    op.drop_index(op.f('ix_pantry_items_user_id'), table_name='pantry_items')
    op.drop_table('pantry_items')
    op.drop_index(op.f('ix_ingestion_jobs_user_id'), table_name='ingestion_jobs')
    op.drop_index(op.f('ix_ingestion_jobs_status'), table_name='ingestion_jobs')
    op.drop_index(op.f('ix_ingestion_jobs_idempotency_key'), table_name='ingestion_jobs')
    op.drop_table('ingestion_jobs')
    op.drop_index(op.f('ix_import_mapping_templates_user_id'), table_name='import_mapping_templates')
    op.drop_table('import_mapping_templates')
    op.drop_index(op.f('ix_import_batches_user_id'), table_name='import_batches')
    op.drop_table('import_batches')
    op.drop_index(op.f('ix_household_members_user_id'), table_name='household_members')
    op.drop_index(op.f('ix_household_members_household_id'), table_name='household_members')
    op.drop_table('household_members')
    op.drop_index(op.f('ix_audit_events_user_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_event_type'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_validation_results_entity_id'), table_name='validation_results')
    op.drop_table('validation_results')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('households')
    # ### end Alembic commands ###

